version: '3'

vars:
  VERSION:
    sh: grep '"version"' web/package.json | head -1 | sed 's/.*"version".*"\([^"]*\)".*/\1/'
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_TIME:
    sh: date -u '+%Y-%m-%dT%H:%M:%SZ'
  LDFLAGS: -X github.com/Bowl42/maxx-next/internal/version.Version={{.VERSION}} -X github.com/Bowl42/maxx-next/internal/version.Commit={{.COMMIT}} -X github.com/Bowl42/maxx-next/internal/version.BuildTime={{.BUILD_TIME}}

tasks:
  dev:
    desc: Run full-stack development (backend + frontend)
    deps: [dev:backend, dev:frontend]

  dev:backend:
    desc: Run backend development server
    cmds:
      - go run cmd/maxx/main.go

  dev:frontend:
    desc: Run frontend development server
    dir: web
    cmds:
      - pnpm dev

  dev:desktop:
    desc: Run Wails desktop application in development mode
    cmds:
      - wails dev

  install:
    desc: Install all dependencies
    cmds:
      - task: install:frontend
      - task: install:wails

  install:frontend:
    desc: Install frontend dependencies
    dir: web
    cmds:
      - pnpm install

  install:wails:
    desc: Install Wails CLI
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest

  build:
    desc: Build complete application (frontend + backend)
    cmds:
      - task: build:frontend
      - task: build:backend

  build:frontend:
    desc: Build frontend
    dir: web
    env:
      VITE_COMMIT: "{{.COMMIT}}"
    cmds:
      - pnpm build

  build:backend:
    desc: Build backend with version info
    cmds:
      - go build -ldflags '{{.LDFLAGS}}' -o maxx cmd/maxx/main.go

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f maxx
      - rm -rf web/dist

  version:
    desc: Show version info
    cmds:
      - 'echo "Version: {{.VERSION}}"'
      - 'echo "Commit:  {{.COMMIT}}"'
      - 'echo "Build:   {{.BUILD_TIME}}"'

  docker:
    desc: Build Docker image
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} --build-arg COMMIT={{.COMMIT}} --build-arg BUILD_TIME={{.BUILD_TIME}} --build-arg VITE_COMMIT={{.COMMIT}} -t maxx .
